name: Listen & Auto-Reply to New Comments

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  reply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install numpy requests tensorflow

      - name: Run comment listener & auto-reply
        env:
          FB_PAGE_ID:    ${{ secrets.FB_PAGE_ID }}
          FB_PAGE_TOKEN: ${{ secrets.FB_TOKEN }}
        run: |
          python scripts/listen_and_reply.py
