name: Publish new properties to Facebook

on:
  schedule:
    - cron: '*/2 * * * *'    # every 2 minutes
  workflow_dispatch:        # manual trigger too

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests firebase-admin

      - name: Publish to Facebook
        env:
          FB_PAGE_ID:          ${{ secrets.FB_PAGE_ID }}
          FB_TOKEN:       ${{ secrets.FB_TOKEN }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          python scripts/publish_to_facebook.py
