name: Scrape & Auto-Reply

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      FB_TOKEN: ${{ secrets.FB_PAGE_TOKEN }}
      PAGE_ID: 579954655210740

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy requests tensorflow

      - name: Scrape Facebook and post replies
        run: python scripts/scrape_and_reply.py

      - name: Generate latest posts JSON
        run: python scripts/dump_posts.py

      - name: Commit & push updated JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: https://x-access-token:${{ secrets.GH_PAT }}@github.com/Simfukwe01/xtraspace-fetcher.git
          branch: main
          commit_message: "chore: update scraped_posts.json"
          file_pattern: scraped_posts.json
          commit_user_name: Simfukwe01
          commit_user_email: Simfukwe01@users.noreply.github.com
